services:
  hangfire.polly:
    image: hangfire.polly
    build:
      context: .
      dockerfile: Hangfire.Polly/Dockerfile

  example.polly:
    image: example.polly
    build:
      context: .
      dockerfile: Example.Polly/Dockerfile
